name: bbaik
favicon: null
layout_spectrum: 0.0143339
typography_spectrum: 0.4021922
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: my personal stuff
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6264756
  lightness: 0.4477234
  saturation: 0.3229342
  rhythmicContrast: 0.4831366
purpose: []
